trigger:
  branches:
    include:
      - feature
    exclude:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install dependencies (Robot Framework, Selenium Library)
- script: |
    pip install --upgrade robotframework-seleniumlibrary
  displayName:  'Install Robot Framework and dependencies'

    # Lägg till ett debug-steg för att se om testfilen finns
- script: ls -R tests/
  displayName: 'Check test folder contents' 

- script: |
      robot --include new-feature 
      --output results/logs/output_feature_test.xml 
      --log results/logs/log_feature_test.html 
      --report results/logs/report_feature_test.html tests/login_page.robot
  displayName: 'Run Tests tagged with new-feature'

  # Publish the Robot Framework reports as pipeline artifacts.
- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-feature'
  displayName: 'Publish Robot Framework Reports'


